[package]
name = "blink_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "blink_core"
path = "src/lib.rs"

[dependencies]
parking_lot = "0.12"
rustyline = "15.0.0"
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
