[package]
name = "blink_sclient"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
